### ISSUE TITLE
HiDPI / Retina Testing

### ISSUE THREAD

**Issue by jean-emmanuel** [jean-emmanuel/open-stage-control#32]
Everything needed to scale the interface is implemented, but no test has been made with HiDPI / Retina devices. Some testing and feedback on this would be greatly appreciated.

**Comment by tristan-k** [comment]
I do have a Microsoft Surface device. I just discovered open-stage-control but I'm happy to help.

**Comment by jean-emmanuel** [comment]
Cool !

Well, I guess the first question would be: does everything renders twice as small as it should ? I'm not sure if chrome takes care of the scaling already...

**Comment by jean-emmanuel** [comment]
I've just pushed a commit that makes the app scale to the device's pixel ratio, the new behavior can be tested at http://demo.osc.ammd.net/, please tell me if it works :)

**Comment by korakios** [comment]
It seems fine in iOS safari browser ,plus web midi browser :)
However in iPhone the menu is a bit messy. If you want I could upload some pictures.
Very interesting project, well done!

**Comment by jean-emmanuel** [comment]
Why not ! Please note that safari is not officially supported though. Only chrome/chromium is, it's available on iOS, isn't it ?

**Comment by tristan-k** [comment]
Works great. Thanks. Though I still dont know how to connect to the interface, I'm having some issues with javascript. Will open another report.

![osc](https://cloud.githubusercontent.com/assets/732025/25001758/397b08ca-2047-11e7-97c4-d12c6904d412.PNG)

**Comment by korakios** [comment]
In iOS ,currently the only browser supporting midi is 'Web Midi Browser'. In the second picture there are the midi IO plus Bluetooth midi.

![img_0259](https://cloud.githubusercontent.com/assets/7697015/25026572/b3889f52-20af-11e7-978b-0412dda4e393.PNG)
![img_0260](https://cloud.githubusercontent.com/assets/7697015/25026573/b3c06734-20af-11e7-90bd-c5f4ab22741c.PNG)

But stage control works on safari browser too (no midi). Those picture where iPad screenshots

**Comment by jean-emmanuel** [comment]
Open Stage Control doesn't rely on browser midi support: osc and midi messages are handled by the server only which communicates with clients through websockets. The visual glitches you're experiencing are a typical example of the cross-browser styling issues that made me limit official support to chrome ;).

**Comment by korakios** [comment]
Ok, I got it! No midi on client browsers! 
The menu 'mess' is also on iphone's Chrome browser, but I think it's normal on such a small screen.

**Comment by jean-emmanuel** [comment]
Alright ! Could you send me some iOS + Chrome screenshot ? What's is your chrome's version btw ?

**Comment by korakios** [comment]
Well ,maybe it was my mistake posting iphone pictures. The dpi is 326 (1136X640) and I don't know if it's considered HiDpi .
Chrome looks exact the same as the last iphone pictures.

**Comment by jean-emmanuel** [comment]
I've pushed 2 commits that aim to fix these glitches (layout mess & input rounded corners), can you try the demo (http://demo.osc.ammd.net) and check if it works ?

**Comment by korakios** [comment]
All good now ! I strongly recommend porting to iOS as a paid app :)

**Comment by jean-emmanuel** [comment]
Hahaha good, thanks for your feedback ! This will be included in the next release coming soon. The app will remain free and open source forever though ;)

**Comment by jean-emmanuel** [comment]
I figured out what was needed to take advantage of high resolution devices. Hdpi support can be enabled by adding `?hdpi=1` to the server's url. It's not enabled by default as I suspect it might have a bad impact on performances with some devices.

You can compare both modes:
- http://openstagecontrol.herokuapp.com/
- http://openstagecontrol.herokuapp.com/?hdpi=1

**Comment by jean-emmanuel** [comment]
The difference consists in upscaling graphics relying on canvas elements to reach the device's resolution (the other elements beeing already scaled natively). On hdpi / mobile devices, widgets should appear less blurry (look at the fader for instance).
