### ISSUE TITLE
Meter on fader and xy pad example

### ISSUE THREAD

**Issue by grizzlymv** [jean-emmanuel/open-stage-control#458]
Hi guys. Not an issue per say but more of a question.   I'm building my screen to interract with my DAW (Cubase) so I can replacey touchosc one, but I'm struggling a bit with 2 things.  First, I'm able to have the faders working without issues. However I've seen there's a meter property which I assume would be to showcase the current meter of that fader, is that right?  If so, would you have an example on how to use it?  

Also.im a bit confused for the xypanel.  I wanted to have 2 CC values controlled (ie x for cc1, y for cc14).  Usually we use the preargs to specify the channel to use (ie [1,1] for cc1 or [1,14] for cc14).  But since it is for 2 axes, how are we suppose to translate that?  The doc is quite thin to address that, but it might just very well just be me who's missing a bit.  ;). Any hint would be appreciated.  And thanks for doing this awesome tool.  Cheers.

**Comment by jean-emmanuel** [comment]
Hi,

The `meter` property adds a [meter widget](http://osc.ammd.net/widgets-reference/#meter) to the fader that  inherits some of its property, its address is the same as the fader's with `/meter` appended to it unless `meterAddress` is set. `preArgs` and `range` are inherited as well. Now there was a bug that prevented the fader's `preArgs` and `address` to properly update the meter upon edition. It's fixed in v0.41.4. 
In order to update the meter's value, one needs to send a value to open-stage-control on its address (`preArgs` must match too, if any). If you need more control over the meter, you can also use the `meter` widget (under "plots").

Please note that MIDI handling is just a conversion layer I added on top of the whole OSC thing, if your software can handle OSC, you should definitely use it over MIDI. 

By default the XY pad sends both coordinates in its osc messages: `/xy_address [preargs] x_value y_value`. To construct your MIDI messages properly you'll need to split these into separate messages:

- create 2 input widgets
- set these widgets' properties as follow:
  - `address`: `/control`
  -  `target`: `midi:your_midi_name` (they will be sending the messages instead of the pad)
  - `preArgs`: `[1, 1]` and `[1, 14]`
  - `value`:  `#{@{xy_id}[0]}` and `#{@{xy_id}[1]}`

The `value` part is written using the [advanced property syntax](http://osc.ammd.net/extras/advanced-property-syntax/) which allows you to connect the widgets between them and do some processing. in this case each input retrieves a subset of the xy pad's value. In details:
- `#{}` encloses a formula
- `@{xy_id}` retrieves the pad's value
- `@{xy_id}[0]` retrieves the first item from the pad's value

**Comment by grizzlymv** [comment]
Thanks a lot for the quick reply.  So after messing around a little more, I'm still unable to have the bundled meter to work (the one that you can activate within the fader).  However, it works with a dedicated meter (which I added from the plots).  Only issue with it is it doesn't seems to properly scale but it's probably something related to my DAW.  

As for the XY pad, it works in the sense that I was able to link the XY Pad with 2 faders using the formula above.  Is it also possible the other way around? ie, having the pad updated as I move the faders?  I would assume so, but I'm confused about how to tell the widget about 2 values instead of the usual 1. I tried #{@{fader_cc1}},#{@{fader_cc14}} without luck.  It works if I try #{@{fader_cc1}} as the value on another fader or meter for instance, so it must be the formatting of my sentence.  I would assume that with 2 values, the first one would be mapped to the X axis and the second one to the Y, but that's unclear.  

Thanks a lot in advance for your tip.

**Comment by jean-emmanuel** [comment]
Almost ! `[@{fader_1}, @{fader_2}]` will do.

**Comment by grizzlymv** [comment]
Yes!! It works perfectly!  I'm having so much fun with this so far.  Thanks again for doing this! :) Keep it up Jean-Emmanuel! 👍

**Comment by jean-emmanuel** [comment]
Thanks :)
